name: Deploy Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout dockerfile'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build builder image'
        run: |
          docker build . --tag ghcr.io/nejtr0n/openwrt-builder:latest
          docker push ghcr.io/nejtr0n/openwrt-builder:latest